version: '3.1'

services:
  oqs_server:
    privileged: true
    build: ./oqs_test
    image: oqs_server_image
    command: /bin/bash -c "source /home/oqs/venv/bin/activate && python3 /home/oqs/oqs_server.py"
    cap_add:
      - NET_ADMIN
    network_mode: "host"

  oqs_client:
    privileged: true
    build: ./oqs_test
    image: oqs_client_image
    command: /bin/bash -c "source /home/oqs/venv/bin/activate && python3 /home/oqs/oqs_client.py"
    depends_on:
      - oqs_server
    cap_add:
      - NET_ADMIN
    network_mode: "host"

  standard_server:
    privileged: true
    build: ./oqs_test
    image: standard_server_image
    command: /bin/bash -c "source /home/oqs/venv/bin/activate && python3 /home/oqs/standard_server.py"
    cap_add:
      - NET_ADMIN
    network_mode: "host"

  standard_client:
    privileged: true
    build: ./oqs_test
    image: standard_client_image
    command: /bin/bash -c "source /home/oqs/venv/bin/activate && python3 /home/oqs/standard_client.py"
    depends_on:
      - standard_server
    cap_add:
      - NET_ADMIN
    network_mode: "host"

