services:
  server:
    image: oqs_server_image
    command: /home/oqs/venv/bin/python3 /home/oqs/server.py

    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - quantum_net
    hostname: server
    volumes:
      - ./server_output.pcap:/home/oqs/server_output.pcap:z

  client:
    image: oqs_server_image
    command: /home/oqs/venv/bin/python3 /home/oqs/client.py

    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - quantum_net
    depends_on:
      - server
    hostname: client
    volumes:
      - ./client_output.pcap:/home/oqs/client_output.pcap:z

networks:
  quantum_net:
    driver: bridge
